# Generated by Django 3.2 on 2022-02-09 11:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bio', models.TextField(verbose_name='Biography')),
                ('user_profile_image', cloudinary.models.CloudinaryField(default='image/upload/leannes_learners/default_image/bio_placeholder', max_length=255)),
                ('user_facebook_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook Link')),
                ('user_twitter_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter Link')),
                ('user_linkedin_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linked-in Link')),
                ('user_website_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Website Link')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
