# Generated by Django 3.2 on 2022-03-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_bio',
            field=models.CharField(blank=True, max_length=2500, verbose_name='Biography'),
        ),
    ]
