# Generated by Django 3.2 on 2022-01-02 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leannes_learners_data', '0002_auto_20211229_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogPost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
