# Generated by Django 3.2 on 2021-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0002_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='slide_text_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homecarousel',
            name='slide_text_headline',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
