# Generated by Django 3.2 on 2021-12-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0002_comment_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_headline', models.CharField(max_length=80, unique=True)),
                ('slide_description', models.CharField(blank=True, max_length=200)),
                ('slide_image', models.CharField(blank=True, max_length=200)),
                ('alt_tag', models.CharField(blank=True, max_length=200)),
                ('include_in_carousel', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-include_in_carousel', '-slide_headline'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
