# Generated by Django 3.2 on 2021-12-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0004_alter_services_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
