# Generated by Django 3.2 on 2022-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0006_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
