# Generated by Django 3.2 on 2022-01-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0007_alter_testimonial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
