# Generated by Django 3.2 on 2021-12-24 05:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0007_alter_services_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='slide_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, unique=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, unique=True, verbose_name='image'),
        ),
    ]
