# Generated by Django 3.2 on 2022-01-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0009_auto_20220104_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
