# Generated by Django 3.2 on 2022-01-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0010_auto_20220104_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeCarousel',
            new_name='Carousel',
        ),
    ]
