# Generated by Django 3.2 on 2022-01-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0012_pupilstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PupilStatus',
        ),
    ]
