# Generated by Django 3.2 on 2022-01-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0014_pass_plus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass_plus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pass Plus Page Content', 'verbose_name_plural': 'Pass Plus Page Content'},
        ),
    ]
