# Generated by Django 3.2 on 2022-01-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0016_auto_20220107_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pass_plus',
            new_name='Passplus',
        ),
    ]
