# Generated by Django 3.2 on 2022-01-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0020_auto_20220109_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passplus',
            old_name='focus_image_alt_tag',
            new_name='alt_tag',
        ),
    ]
