# Generated by Django 3.2 on 2022-01-13 13:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0022_contactdetails_teachinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('social_media_name_1', models.CharField(blank=True, max_length=80)),
                ('social_media_link_1', models.CharField(blank=True, max_length=200)),
                ('social_media_image_1', cloudinary.models.CloudinaryField(default='placeholder', max_length=255)),
                ('social_media_name_2', models.CharField(blank=True, max_length=80)),
                ('social_media_link_2', models.CharField(blank=True, max_length=200)),
                ('social_media_image_2', cloudinary.models.CloudinaryField(default='placeholder', max_length=255)),
                ('social_media_name_3', models.CharField(blank=True, max_length=80)),
                ('social_media_link_3', models.CharField(blank=True, max_length=200)),
                ('social_media_image_3', cloudinary.models.CloudinaryField(default='placeholder', max_length=255)),
                ('social_media_name_4', models.CharField(blank=True, max_length=80)),
                ('social_media_link_4', models.CharField(blank=True, max_length=200)),
                ('social_media_image_4', cloudinary.models.CloudinaryField(default='placeholder', max_length=255)),
            ],
            options={
                'verbose_name': 'Contact/Social Information',
                'verbose_name_plural': 'Contact/Social Information',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Contactdetails',
        ),
    ]
