# Generated by Django 3.2 on 2022-01-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0025_auto_20220113_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name': 'Company Contact/Social Information', 'verbose_name_plural': 'Company Contact/Social Information'},
        ),
        migrations.RenameField(
            model_name='companydetails',
            old_name='social_media_image_1',
            new_name='social_media_image',
        ),
    ]
