# Generated by Django 3.2 on 2022-01-21 04:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0027_remove_companydetails_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_and_Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255)),
                ('lead_content', models.TextField()),
                ('main_content', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
            options={
                'verbose_name': 'Terms and Conditions Page Content',
                'verbose_name_plural': 'Terms and Conditions Page Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
