# Generated by Django 3.2 on 2022-01-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0029_auto_20220126_0510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermsAndConditions',
            new_name='Terms',
        ),
    ]
