# Generated by Django 3.2 on 2022-01-27 12:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0033_auto_20220127_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passplus',
            name='lead_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
