# Generated by Django 3.2 on 2022-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0034_alter_passplus_lead_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe the image for the blind'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='slide_text_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe the image for the blind'),
        ),
        migrations.AlterField(
            model_name='passplus',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe the image for the blind'),
        ),
        migrations.AlterField(
            model_name='passplus',
            name='lead_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='passplus',
            name='main_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='terms',
            name='lead_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='terms',
            name='main_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe the image for the blind'),
        ),
    ]
