# Generated by Django 3.2 on 2022-01-28 20:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0035_auto_20220127_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='passplus',
            name='lead_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Lead content - more prominent than the rest.'),
        ),
        migrations.AlterField(
            model_name='passplus',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Main content of the page.'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='lead_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Lead content - The explanation.'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='main_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='The Terms and Conditions.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
