# Generated by Django 3.2 on 2022-03-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0038_auto_20220302_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='page_title',
            field=models.CharField(default='1', max_length=160, verbose_name='Page Title '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='seo_keywords',
            field=models.CharField(max_length=160, verbose_name='Page Keywords - seperate by a comma'),
        ),
    ]
