# Generated by Django 3.2 on 2022-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0041_service_featured_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='featured_order',
            field=models.IntegerField(verbose_name='Featured Price Order results display 1,2,3'),
        ),
    ]
