# Generated by Django 3.2 on 2022-03-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0042_alter_service_featured_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='passplus',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='background_image',
        ),
    ]
