# Generated by Django 3.2 on 2022-03-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0043_auto_20220302_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='seo_description',
            field=models.CharField(default='', max_length=150, verbose_name='Google search description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='seo_title',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Page tab title'),
            preserve_default=False,
        ),
    ]
