# Generated by Django 3.2 on 2022-03-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0045_auto_20220303_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='passplus',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='passplus',
            name='seo_title',
        ),
    ]
