# Generated by Django 3.2 on 2022-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leannes_learners_data', '0046_auto_20220303_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='image alternative text'),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='image alternative text'),
        ),
        migrations.AlterField(
            model_name='passplus',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='image alternative text'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='image alternative text'),
        ),
    ]
