# Generated by Django 3.2 on 2022-01-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe image for the blind'),
        ),
    ]
