# Generated by Django 3.2 on 2022-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_alt_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe the image for the blind'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Eye Catching Excerpt - make someone want to read the article'),
        ),
    ]
