# Generated by Django 3.2 on 2022-02-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220203_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alt_tag',
            field=models.CharField(max_length=200, verbose_name='Describe the image for the blind'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(verbose_name='Eye Catching Excerpt - make someone want to read the article'),
        ),
    ]
