# Generated by Django 3.2 on 2022-01-27 21:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Eye Catching Excerpt - make someone want to read the article'),
        ),
    ]
