# Generated by Django 3.2 on 2022-02-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio_image',
            new_name='user_profile_image',
        ),
    ]
