# Generated by Django 3.2 on 2022-02-08 06:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220208_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=cloudinary.models.CloudinaryField(default='bio_placeholder', max_length=255),
        ),
    ]
