# Generated by Django 3.2 on 2022-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_facebook_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Linked-in Link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_twitter_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter Link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_website_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Describe the image for the blind'),
        ),
    ]
