# Generated by Django 3.2 on 2022-02-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20220209_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
