# Generated by Django 3.2 on 2022-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(verbose_name='Eye Catching Excerpt - make someone want to read the article'),
        ),
    ]
