# Generated by Django 3.2 on 2022-03-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_comment_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_profile_image',
        ),
    ]
