# Generated by Django 3.2 on 2022-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_comment_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=200, verbose_name='image alternative text'),
        ),
    ]
