# Generated by Django 3.2 on 2022-03-04 09:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_post_alt_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=60, populate_from='name', unique=True),
        ),
    ]
