# Generated by Django 3.2 on 2022-03-14 05:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=60, populate_from='title', unique=True),
        ),
    ]
